# Generated by Django 5.1.5 on 2025-02-28 05:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Morita, mi perrita', max_length=300)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lirio, mi perro igual', max_length=100)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(default=0.0)),
                ('tipo_boleto_id', models.IntegerField(default=1)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='examen.evento')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='localidad_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='examen.localidad'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nutella, mi perro', max_length=200)),
                ('precio', models.FloatField(default=0.0)),
                ('localidad_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='examen.localidad')),
            ],
        ),
    ]
