# Generated by Django 5.1.5 on 2025-03-05 01:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
