# Generated by Django 5.1.5 on 2025-02-13 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=18)),
                ('rfc', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('updated_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('zip_code', models.IntegerField(default=0, max_length=8)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('updated_date', models.DateTimeField(verbose_name='date published')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.user')),
            ],
        ),
    ]
