# Generated by Django 5.1.5 on 2025-02-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
